name: custom_social_share
description: "Flutter plugin for sharing text content to most popular social media apps."
version: 1.0.9
homepage: https://github.com/keval-devani/custom_social_share

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.5.0'


dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.kd.custom_social_share
        pluginClass: CustomSocialSharePlugin
      ios:
        pluginClass: CustomSocialSharePlugin
